version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/affpilot_content_generator

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: affpilot_content_generator
    volumes:
      - postgres_data:/var/lib/postgresql/data
  

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery --app=app.tasks.celery.celery_app worker --pool=solo --loglevel=DEBUG
    volumes:
      - .:/app
      - ./celery_data:/app/celery_data  
    depends_on:
      - web
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/affpilot_content_generator

volumes:
  postgres_data:
