"""Initial migration

Revision ID: 3bdd6ca0aba9
Revises: 78235bd607df
Create Date: 2025-09-24 14:51:53.292909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bdd6ca0aba9'
down_revision: Union[str, Sequence[str], None] = '78235bd607df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_designs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('custom_text', sa.String(length=255), nullable=False),
    sa.Column('font_style', sa.String(length=50), nullable=True),
    sa.Column('text_color', sa.String(length=20), nullable=True),
    sa.Column('text_position_x', sa.Integer(), nullable=True),
    sa.Column('text_position_y', sa.Integer(), nullable=True),
    sa.Column('preview_image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_designs_id'), 'product_designs', ['id'], unique=False)
    op.drop_column('products', 'customize_count')
    op.drop_column('products', 'custom_text')
    op.drop_column('products', 'last_customized_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('last_customized_at', mysql.DATETIME(), nullable=True))
    op.add_column('products', sa.Column('custom_text', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('products', sa.Column('customize_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_product_designs_id'), table_name='product_designs')
    op.drop_table('product_designs')
    # ### end Alembic commands ###
