"""Initial migration

Revision ID: 78235bd607df
Revises: 
Create Date: 2025-09-24 09:57:49.847513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78235bd607df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apis',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('OPENAI', 'GROK', 'DEEPSEEK', 'GEMINI', 'TWITTER', 'LINKEDIN', 'FACEBOOK', 'INSTAGRAM', name='apitype'), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('access_key', sa.String(length=512), nullable=False),
    sa.Column('secret_key', sa.String(length=512), nullable=True),
    sa.Column('load', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apis_id'), 'apis', ['id'], unique=False)
    op.create_table('images',
    sa.Column('type', sa.Enum('URL', 'FILE', name='imagetype'), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('social_platforms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('TWITTER', 'LINKEDIN', 'FACEBOOK', 'INSTAGRAM', name='platformtype'), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'EXPIRED', name='platformstatus'), nullable=True),
    sa.Column('api_id', sa.String(length=255), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_platforms_id'), 'social_platforms', ['id'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_text', sa.String(length=255), nullable=True),
    sa.Column('customize_count', sa.Integer(), nullable=False),
    sa.Column('last_customized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.Enum('SHIRT', 'T_SHIRT', 'PANT', 'JACKET', 'HOODIE', 'DRESS', name='productcategory'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sell_count', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('ongoing_order', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'CAROUSEL', 'STORY', 'REEL', name='posttype'), nullable=False),
    sa.Column('content_text', sa.JSON(), nullable=False),
    sa.Column('content_tone', sa.Enum('PROFESSIONAL', 'CASUAL', 'FRIENDLY', 'FORMAL', 'HUMOROUS', name='posttone'), nullable=True),
    sa.Column('platform_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('image_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'PENDING', 'SCHEDULED', 'FAILED', name='poststatus'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('api_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['social_platforms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('insight_type', sa.Enum('ENGAGEMENT', 'TIMING', 'CONTENT', 'HASHTAG', 'AUDIENCE', 'PERFORMANCE', name='insighttype'), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    op.create_table('post_analyses',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('ai_insight_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_insight_id'], ['ai_insights.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_analyses_id'), 'post_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_analyses_id'), table_name='post_analyses')
    op.drop_table('post_analyses')
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_social_platforms_id'), table_name='social_platforms')
    op.drop_table('social_platforms')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_apis_id'), table_name='apis')
    op.drop_table('apis')
    # ### end Alembic commands ###
